on:
  push:
    branches:
      - main
name: Deploy Main on Push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use production env
      run: cp .env.example .env
    
    - name: Install vendors
      run: composer install --no-dev --optimize-autoloader

    - name: Delete cache
      run: rm -rf /bootstrap/cache/*

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 184.168.113.105
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
